//
//  DashboardRouter.swift
//  Movie_Clean_Swift
//
//  Created by Álvaro Fernandes on 15/01/20.
//  Copyright (c) 2020 Álvaro Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DashboardRoutingLogic {
  
}

protocol DashboardDataPassing {
  var dataStore: DashboardDataStore? { get }
}

class DashboardRouter: NSObject, DashboardRoutingLogic, DashboardDataPassing {
    
    weak var viewController: DashboardViewController?
    var dataStore: DashboardDataStore?
  
//    func routeToAny(){
//        guard let destinationVC = NextViewController() else { return }
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
//    }
//
//    func passDataToSomewhere(source: DashboardDataStore, destination: inout NextDataStore) {
//      destination.session = source.session
//    }
}
