//
//  DashboardWorker.swift
//  Movie_Clean_Swift
//
//  Created by Álvaro Fernandes on 15/01/20.
//  Copyright (c) 2020 Álvaro Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class DashboardWorker  {
    let networkProvider: NetworkProvider

    init(networkProvider: NetworkProvider = NetworkProvider()) {
        self.networkProvider = networkProvider
    }

    func getMovies(_ requestProvider: RequestProvider) -> Promise<HomeMovieModels.MovieApiResponse> {
        return networkProvider.execute(request: requestProvider, parser: HomeMovieModels.MovieApiResponse.self)
    }


}
