//
//  DashboardViewController.swift
//  Movie_Clean_Swift
//
//  Created by Álvaro Fernandes on 15/01/20.
//  Copyright (c) 2020 Álvaro Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardDisplayLogic: class {
  
}

class DashboardViewController: UICollectionViewController {
    
    var interactor: DashboardBusinessLogic?
    var router: (NSObjectProtocol & DashboardRoutingLogic & DashboardDataPassing)?
    
    override func loadView() {
        super.loadView()
        setup()
    }
    
    private func setup() {
        let viewController = self
        let interactor = DashboardInteractor()
        let presenter = DashboardPresenter()
        let router = DashboardRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    override func numberOfSections(in collectionView: UICollectionView) -> Int {
//        interactor?.numberOfSections()
        return 0
    }
}

extension DashboardViewController: DashboardDisplayLogic {
    
}
