//
//  DetailWorker.swift
//  Movie_Clean_Swift
//
//  Created by Álvaro Fernandes on 12/01/20.
//  Copyright (c) 2020 Álvaro Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class DetailWorker  {
    let networkProvider: NetworkProvider

    init(networkProvider: NetworkProvider = NetworkProvider()) {
        self.networkProvider = networkProvider
    }

//    func getData() -> Promise<DetailModels> {
////        let requestProvider = HomeProvider()
////        return networkProvider.execute(request: requestProvider, parser: DetailModel.self)
//    }

}
