//
//  DetailInteractor.swift
//  Movie_Clean_Swift
//
//  Created by Álvaro Fernandes on 12/01/20.
//  Copyright (c) 2020 Álvaro Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func load()
}

protocol DetailDataStore {
  //var name: String { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    
    var presenter: DetailPresentationLogic?
    var worker: DetailWorker?
    
    init(worker: DetailWorker = DetailWorker()) {
      self.worker = worker
    }
    
    func load() {
       // worker.getData().done(handleSuccess).catch(handleFailure)
    }

    
}
