//
//  HomeMoviePresenter.swift
//  Movie_Clean_Swift
//
//  Created by Álvaro Fernandes on 30/12/19.
//  Copyright (c) 2019 Álvaro Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeMoviePresentationLogic {
    func reloadTableView()
    func showError()
}

class HomeMoviePresenter: HomeMoviePresentationLogic {
    
    weak var viewController: HomeMovieDisplayLogic?
    
    func reloadTableView() {
        viewController?.reloadTableView()
    }
    
    func showError() {
        let title = "Desculpe pelo erro =("
        let message = "Tivemos um problema em carregar sua página, clique novamente em 'Eu quero mais!' para carregarmos a próxima"
        viewController?.showError(title, message)
    }
  
}
