//
//  HomeMovieRouter.swift
//  Movie_Clean_Swift
//
//  Created by Álvaro Fernandes on 30/12/19.
//  Copyright (c) 2019 Álvaro Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeMovieRoutingLogic {
  
}

protocol HomeMovieDataPassing {
  var dataStore: HomeMovieDataStore? { get }
}

class HomeMovieRouter: NSObject, HomeMovieRoutingLogic, HomeMovieDataPassing {
    
    weak var viewController: HomeMovieViewController?
    var dataStore: HomeMovieDataStore?
  
//    func routeToAny(){
//        guard let destinationVC = NextViewController() else { return }
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
//    }
//
//    func passDataToSomewhere(source: HomeMovieDataStore, destination: inout NextDataStore) {
//      destination.session = source.session
//    }
}
