//
//  HomeMovieRouter.swift
//  Movie_Clean_Swift
//
//  Created by Álvaro Fernandes on 30/12/19.
//  Copyright (c) 2019 Álvaro Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeMovieRoutingLogic {
    func showError(_ title: String, _ message: String)
}

protocol HomeMovieDataPassing {
    var dataStore: HomeMovieDataStore? { get }
}

class HomeMovieRouter: NSObject, HomeMovieRoutingLogic, HomeMovieDataPassing {

    weak var viewController: HomeMovieViewController?
    var dataStore: HomeMovieDataStore?
    
    func showError(_ title: String, _ message: String) {
        showAlert(title, message)
    }
    
    private func showAlert(_ title: String, _ message: String) {
        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let action = UIAlertAction(title: "OK", style: .default) { (action) in
        }
        alert.addAction(action)
        viewController?.present(alert, animated: true, completion: nil)
    }
    
}
