//
//  HomeMovieWorker.swift
//  Movie_Clean_Swift
//
//  Created by Álvaro Fernandes on 30/12/19.
//  Copyright (c) 2019 Álvaro Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class HomeMovieWorker  {
    
    let networkProvider: NetworkProvider

    init(networkProvider: NetworkProvider = NetworkProvider()) {
        self.networkProvider = networkProvider
    }

    func getData(movieApi: MovieApi, page: Int) -> Promise<HomeMovieModels.MovieApiResponse> {
        print(movieApi)
        let requestProvider = HomeMovieProvider(movieApi: movieApi, page: page)
        return networkProvider.execute(request: requestProvider, parser: HomeMovieModels.MovieApiResponse.self)
    }

}
